"""Base entity class for all database models"""

import re
from datetime import datetime

from sqlalchemy import BigInteger
from sqlalchemy import DateTime
from sqlalchemy import Identity
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import declared_attr
from sqlalchemy.orm import mapped_column
from sqlalchemy.sql import func


# Naming convention for all indexes and constraints
# This ensures consistent, predictable constraint names across the database
# See why this is important and how it would save your time:
# https://alembic.sqlalchemy.org/en/latest/naming.html
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",  # Index: ix_column_name
    "uq": "uq_%(table_name)s_%(column_0_name)s",  # Unique: uq_table_column
    "ck": "ck_%(table_name)s_%(constraint_name)s",  # Check: ck_table_constraint
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",  # Foreign key: fk_table_column_referred
    "pk": "pk_%(table_name)s",  # Primary key: pk_table
}


class Entity(DeclarativeBase):
    """
    Base class for all domain entities.

    All domain entities should inherit from this class.

    Provides:
    - an Auto-discovery mechanism for Alembic migrations
    - Async session support
    - Naming conventions for all constraints and indexes
    - Auto-generated id field (BigInteger with Identity)
    - Auto-generated table names (CamelCase → snake_case + 's')
    - Common __repr__ method

    Naming Convention Format:
    - Indexes: ix_column_name
    - Unique constraints: uq_table_column
    - Check constraints: ck_table_constraint
    - Foreign keys: fk_table_column_referred
    - Primary keys: pk_table

    Fields:
    - pk: Primary key (BigInteger with Identity, auto-generated by default)
         Database column name: "id"
         Uses GENERATED BY DEFAULT AS IDENTITY for flexibility
         Allows manual ID insertion when needed (testing, data migration)
    """

    __abstract__ = True

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    pk: Mapped[int] = mapped_column("id", BigInteger, Identity(always=True), primary_key=True)

    @declared_attr.directive
    def __tablename__(self) -> str:
        # Convert camel case to snake case
        name = re.sub(r"(?<!^)(?=[A-Z])", "_", self.__name__).lower()

        # Add 's' at the end for pluralization
        return f"{name}s"

    def __repr__(self) -> str:
        """String representation of the entity"""
        return f"<Entity {self.__class__.__name__} #{self.pk}>"


class TimeStampMixin:
    """Mixin class to track creation and update timestamps."""

    __abstract__ = True

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class StatusMixin:
    """Mixin class to provide status-related functionality."""

    __abstract__ = True

    is_locked: Mapped[bool] = mapped_column(default=False)

    @property
    def is_active(self) -> bool:
        return not self.is_locked

    @is_active.setter
    def is_active(self, value: bool) -> None:
        self.is_locked = not value  # type: ignore
